name = "wecare-onboarding"
main = "worker.js"
compatibility_date = "2026-06-01"

[[kv_namespaces]]
binding = "ONBOARDING_KV"
id = "a93c0bc253924254a01df4112be42672"

[vars]
AUTH_TOKEN = "wecare_sync_7k2p9m"

[ai]
binding = "AI"
